### ISSUE TITLE
Song Text issues on Random Mode

### ISSUE THREAD

**Issue by huffstler** [GoneMADSoftware/gmmp-dev#1]
While on full random mode, if you go back to a previous song that played and then look at the queue, the song you were originally on is still there. Though some text will update.

As an aside, I really hope you keep an eye on this repo. It seems like it's not being used

**Comment by GoneMADSoftware** [comment]
It has nothing to do with random mode,  the queue stays accurate 99 percent
of the time,  but yes you are right sometimes it does not refresh after
changing tracks.  I have not been able to track down the issue yet
